# -*- coding: utf-8 -*-
"""PRMLproj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16kl_OV6paINAvDE44ofqz11cFfHpCvmW
"""


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from scipy import stats
from scipy.stats import mannwhitneyu

# -- Aesthetics ----------------------------------------------------------------
PALETTE   = {"Healthy": "#2196A3", "Alzheimer": "#E05A3A"}
COLORS    = [PALETTE["Healthy"], PALETTE["Alzheimer"]]
sns.set_theme(style="whitegrid", font_scale=1.1)
plt.rcParams.update({"figure.dpi": 120, "axes.spines.top": False,
                     "axes.spines.right": False})

# -- Device --------------------------------------------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Hardware: PyTorch MLP will run on {device}")

df = pd.read_csv('data.csv')
X = df.drop(columns=['ID', 'class'], errors='ignore')
y_raw = df[['class']]

le = LabelEncoder()
y = le.fit_transform(y_raw.values.ravel())   # H -> 0, P -> 1

print(f"Dataset loaded: {X.shape[0]} samples × {X.shape[1]} features")
print(f"Classes: {dict(zip(le.classes_, np.bincount(y)))}")

X_cv, X_holdout, y_cv, y_holdout = train_test_split(
    X, y, test_size=0.20, stratify=y, random_state=42
)
print(f"\nSplit -> CV pool: {X_cv.shape[0]} | Holdout: {X_holdout.shape[0]}")

# Attach label column for EDA convenience
df_eda = X_cv.copy()
df_eda['Label'] = pd.Categorical(
    np.where(y_cv == 0, "Healthy", "Alzheimer"),
    categories=["Healthy", "Alzheimer"]
)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

counts = df_eda['Label'].value_counts()
axes[0].bar(counts.index, counts.values, color=COLORS, edgecolor='white', width=0.5)
for i, (lbl, cnt) in enumerate(counts.items()):
    axes[0].text(i, cnt + 0.5, str(cnt), ha='center', fontweight='bold', fontsize=13)
axes[0].set_title("Class Distribution", fontsize=14, fontweight='bold')
axes[0].set_ylabel("Number of Subjects")
axes[0].set_ylim(0, counts.max() * 1.15)

axes[1].pie(counts.values, labels=counts.index, autopct='%1.1f%%',
            colors=COLORS, startangle=90,
            wedgeprops=dict(edgecolor='white', linewidth=2))
axes[1].set_title("Class Balance (%)", fontsize=14, fontweight='bold')

plt.suptitle("3.1 - Class Distribution", fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# -- 3.2 Missing values & basic statistics ------------------------------------
missing = X_cv.isnull().sum()
print("\n-- Missing Values ----------------------------------")
print(f"Total features with missing data: {(missing > 0).sum()} / {X_cv.shape[1]}")

desc = X_cv.describe().T
fig, axes = plt.subplots(1, 2, figsize=(18, 4))

axes[0].scatter(desc['mean'], desc['std'], alpha=0.5, color='#E05A3A', s=20)
axes[0].set_title("Mean vs Std Dev (spread map)", fontsize=12, fontweight='bold')
axes[0].set_xlabel("Mean"); axes[1].set_ylabel("Std Dev")

skewness = X_cv.skew().sort_values()
axes[1].hist(skewness, bins=40, color='#2196A3', edgecolor='white', alpha=0.85)
axes[1].axvline(0, color='red', linestyle='--', linewidth=1.5, label='Symmetry line')
axes[1].set_title("Distribution of Feature Skewness", fontsize=12, fontweight='bold')
axes[1].set_xlabel("Skewness"); axes[1].set_ylabel("Count")
axes[1].legend()

plt.suptitle("3.2 - Feature-Level Statistics Overview", fontsize=15,
             fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()
# -- 3.3 Top discriminating feature distributions -----------------------------
correlations = X_cv.corrwith(pd.Series(y_cv, index=X_cv.index))
top_pos = correlations.nlargest(5).index.tolist()
top_neg = correlations.nsmallest(5).index.tolist()
top10   = top_neg + top_pos   # ordered: most negative -> most positive

fig, axes = plt.subplots(2, 5, figsize=(22, 8))
for ax, feat in zip(axes.flatten(), top10):
    for label, color in PALETTE.items():
        subset = df_eda[df_eda['Label'] == label][feat]
        sns.kdeplot(subset, ax=ax, fill=True, color=color,
                    alpha=0.45, label=label, linewidth=1.5)
    corr_val = correlations[feat]
    ax.set_title(f"{feat}\n(r = {corr_val:.3f})", fontsize=9, fontweight='bold')
    ax.set_xlabel(""); ax.tick_params(axis='x', rotation=30)
    ax.legend(fontsize=7)

plt.suptitle("3.3 - KDE Distributions of Top 10 Discriminating Features",
             fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()
# -- 3.6 Correlation heatmap (top 20 features by absolute correlation) ---------
top20 = correlations.abs().nlargest(20).index.tolist()
corr_matrix = X_cv[top20].corr()

fig, ax = plt.subplots(figsize=(14, 11))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, cmap='RdBu_r', center=0,
            vmin=-1, vmax=1, annot=True, fmt='.2f',
            annot_kws={'size': 7}, linewidths=0.3,
            square=True, ax=ax, cbar_kws={'shrink': 0.8})
ax.set_title("3.6 - Inter-Feature Correlation Heatmap (Top 20 Discriminating Features)",
             fontsize=13, fontweight='bold', pad=15)
ax.tick_params(axis='x', rotation=45, labelsize=8)
ax.tick_params(axis='y', rotation=0,  labelsize=8)
plt.tight_layout()
plt.show()
# -- 3.7 Target correlation bar chart (full ranking) ---------------------------
fig, ax = plt.subplots(figsize=(14, 5))
corr_sorted = correlations.sort_values()
bar_colors  = [PALETTE["Alzheimer"] if v > 0 else PALETTE["Healthy"]
               for v in corr_sorted.values]
ax.bar(range(len(corr_sorted)), corr_sorted.values, color=bar_colors, alpha=0.75, width=1.0)
ax.axhline(0, color='black', linewidth=0.8)
ax.set_xticks([]); ax.set_xlabel("Features (sorted by correlation)")
ax.set_ylabel("Pearson r with Target")
ax.set_title("3.7 - All-Feature Correlation with Target Label\n"
             "(Red = positively linked to Alzheimer, Blue = negatively linked)",
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# -- 3.8 Feature group analysis ------------------------------------------------
# DARWIN features are named like: air_time1, pressure5, gmrt_in_air3 ...
# Extract the base metric name (everything before the trailing digit(s))
import re

def get_group(col):
    return re.sub(r'\d+$', '', col)

groups = pd.Series({col: get_group(col) for col in X_cv.columns})
group_mean_corr = correlations.groupby(groups).mean().sort_values()

fig, ax = plt.subplots(figsize=(14, max(5, len(group_mean_corr) * 0.35)))
bar_col = [PALETTE["Alzheimer"] if v > 0 else PALETTE["Healthy"]
           for v in group_mean_corr.values]
ax.barh(group_mean_corr.index, group_mean_corr.values, color=bar_col, alpha=0.8)
ax.axvline(0, color='black', linewidth=0.8)
ax.set_xlabel("Mean Pearson r with Target")
ax.set_title("3.8 - Mean Discriminative Power by Handwriting Feature Group",
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# Mean signal per subject
subject_mean = X_cv.mean(axis=1)

# Create the figure for 3.10 plots
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for lbl, color, val in zip(["Healthy", "Alzheimer"], COLORS, [0, 1]):
    mask = y_cv == val
    axes[0].hist(subject_mean[mask], bins=25, color=color, alpha=0.6,
                 label=lbl, edgecolor='white', density=True)
    axes[0].axvline(subject_mean[mask].mean(), color=color,
                    linestyle='--', linewidth=2, label=f"{lbl} mean")
axes[0].set_title("3.10a - Distribution of Per-Subject Feature Mean",
                  fontsize=12, fontweight='bold')
axes[0].set_xlabel("Mean Feature Value"); axes[0].legend(fontsize=8)

# Feature value spread (IQR) per class
iqr_h = X_cv[y_cv == 0].apply(lambda c: c.quantile(0.75) - c.quantile(0.25))
iqr_a = X_cv[y_cv == 1].apply(lambda c: c.quantile(0.75) - c.quantile(0.25))
axes[1].scatter(iqr_h, iqr_a, alpha=0.35, s=15, color='#7B68EE')
lim = max(iqr_h.max(), iqr_a.max()) * 1.05
axes[1].plot([0, lim], [0, lim], 'r--', linewidth=1.2, label='Equal IQR')
axes[1].set_title("3.10b - IQR Comparison per Feature (Healthy vs Alzheimer)",
                  fontsize=12, fontweight='bold')
axes[1].set_xlabel("IQR - Healthy"); axes[1].set_ylabel("IQR - Alzheimer")
axes[1].legend()

plt.suptitle("3.10 - Signal Spread & Variability Analysis",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()
# 1. Setup and Dimensionality Reduction
scaler_eda = StandardScaler()
X_cv_sc    = scaler_eda.fit_transform(X_cv)

pca_model = PCA(n_components=2)
pca2      = pca_model.fit_transform(X_cv_sc)

lda_model = LDA(n_components=1)
lda1      = lda_model.fit_transform(X_cv_sc, y_cv).flatten()

# 2. Create the Figure
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# --- Plot 1: PCA 2D Projection (axes[0]) ---
for lbl, color, val in zip(["Healthy", "Alzheimer"], COLORS, [0, 1]):
    mask = y_cv == val
    axes[0].scatter(pca2[mask, 0], pca2[mask, 1],
                    c=color, label=lbl, alpha=0.65, s=55, edgecolors='white', linewidths=0.5)

axes[0].set_title("3.9a - PCA 2D Projection", fontsize=13, fontweight='bold')
axes[0].set_xlabel(f"PC1 ({pca_model.explained_variance_ratio_[0]*100:.1f}% var)")
axes[0].set_ylabel(f"PC2 ({pca_model.explained_variance_ratio_[1]*100:.1f}% var)")
axes[0].legend()

# --- Plot 2: LDA 1D Projection with Jitter (axes[1]) ---
# Generate random jitter for the y-axis to separate overlapping points
jitter = np.random.default_rng(0).normal(0, 0.08, size=len(lda1))

for lbl, color, val in zip(["Healthy", "Alzheimer"], COLORS, [0, 1]):
    mask = y_cv == val
    axes[1].scatter(lda1[mask], jitter[mask],
                    c=color, label=lbl, alpha=0.65, s=55, edgecolors='white', linewidths=0.5)

axes[1].set_title("3.9b - LDA 1D Projection (jittered for visibility)", fontsize=13, fontweight='bold')
axes[1].set_xlabel("Linear Discriminant 1")
axes[1].set_yticks([]) # Hide y-axis ticks since the y-values are just random jitter
axes[1].legend()

# 3. Final Formatting and Display
plt.suptitle("3.9 - Dimensionality Reduction: Cluster Separation", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

top4 = correlations.abs().nlargest(4).index.tolist()
pp_df = df_eda[top4 + ['Label']].copy()

g = sns.pairplot(pp_df, hue='Label', palette=PALETTE,
                 plot_kws=dict(alpha=0.55, s=40, edgecolor='white', linewidth=0.3),
                 diag_kind='kde', diag_kws=dict(fill=True, alpha=0.5))
g.fig.suptitle("3.12 - Pairplot: Top 4 Discriminating Features",
               fontsize=14, fontweight='bold', y=1.02)
plt.show()

scaler = StandardScaler()
X_cv_scaled      = scaler.fit_transform(X_cv)
X_holdout_scaled = scaler.transform(X_holdout)

# ============================================================================
# 5. DIMENSIONALITY REDUCTION ANALYSIS
# ============================================================================
pca_full = PCA().fit(X_cv_scaled)
cum_var  = np.cumsum(pca_full.explained_variance_ratio_)
n_components_pca = np.argmax(cum_var >= 0.95) + 1

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(range(1, len(cum_var) + 1), cum_var, color='steelblue', lw=2)
axes[0].fill_between(range(1, len(cum_var) + 1), cum_var, alpha=0.15, color='steelblue')
axes[0].axhline(y=0.95, color='red', linestyle='--', label='95% threshold')
axes[0].axvline(x=n_components_pca, color='green', linestyle=':',
                label=f'Elbow: {n_components_pca} components')
axes[0].set_title("PCA Elbow Plot", fontsize=13, fontweight='bold')
axes[0].set_xlabel("Number of Components"); axes[0].set_ylabel("Cumulative Variance")
axes[0].legend()
lda_viz = LDA(n_components=1).fit_transform(X_cv_scaled, y_cv)
for lbl, color, val in zip(["Healthy", "Alzheimer"], COLORS, [0, 1]):
    sns.kdeplot(lda_viz[y_cv == val].flatten(), fill=True, color=color,
                label=lbl, ax=axes[1], alpha=0.5)
axes[1].set_title("LDA: 1D Class Separation", fontsize=13, fontweight='bold')
axes[1].set_xlabel("Linear Discriminant 1"); axes[1].legend()

plt.suptitle("5. - Dimensionality Reduction", fontsize=14, fontweight='bold')
plt.tight_layout(); plt.show()

print(f"PCA: {n_components_pca} components retain 95% variance.")

# LDA feature weights
lda_full = LDA(n_components=1).fit(X_cv_scaled, y_cv)
feature_importance = pd.DataFrame({
    'Feature': X_cv.columns,
    'Weight': np.abs(lda_full.coef_[0])
}).sort_values(by='Weight', ascending=False)

fig, ax = plt.subplots(figsize=(12, 8))
sns.barplot(x='Weight', y='Feature', data=feature_importance.head(20),
            palette='rocket', ax=ax)
ax.set_title("Top 20 Most Influential Features (LDA Weights)",
             fontsize=13, fontweight='bold')
plt.tight_layout(); plt.show()

class HandwritingMLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 64), nn.ReLU(), nn.Dropout(0.2),
            nn.Linear(64, 32),        nn.ReLU(),
            nn.Linear(32, 2)
        )
    def forward(self, x): return self.net(x)

def run_mlp_cuda(X_tr, y_tr, X_te):
    X_tr_t = torch.FloatTensor(X_tr).to(device)
    y_tr_t = torch.LongTensor(y_tr).to(device)
    X_te_t = torch.FloatTensor(X_te).to(device)
    model  = HandwritingMLP(X_tr.shape[1]).to(device)
    opt    = optim.Adam(model.parameters(), lr=0.002, weight_decay=1e-4)
    crit   = nn.CrossEntropyLoss()
    for _ in range(150):
        model.train(); opt.zero_grad()
        crit(model(X_tr_t), y_tr_t).backward(); opt.step()
    model.eval()
    with torch.no_grad():
        return torch.max(model(X_te_t), 1)[1].cpu().numpy()

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
comparison_data = []

print("Running 5-fold cross-validation …")
for train_idx, val_idx in skf.split(X_cv_scaled, y_cv):
    X_tr_raw, X_val_raw = X_cv_scaled[train_idx], X_cv_scaled[val_idx]
    y_tr, y_val         = y_cv[train_idx],         y_cv[val_idx]

    for tech in ['PCA', 'LDA']:
        reducer  = PCA(n_components=n_components_pca) if tech == 'PCA' else LDA(n_components=1)
        X_tr_r   = reducer.fit_transform(X_tr_raw, y_tr)
        X_val_r  = reducer.transform(X_val_raw)

        knn = KNeighborsClassifier(n_neighbors=5, weights='distance').fit(X_tr_r, y_tr)
        comparison_data.append({'Technique': tech, 'Model': 'KNN',
                                 'Accuracy': accuracy_score(y_val, knn.predict(X_val_r))})

        svm = SVC(kernel='linear', C=0.5).fit(X_tr_r, y_tr)
        comparison_data.append({'Technique': tech, 'Model': 'SVM',
                                 'Accuracy': accuracy_score(y_val, svm.predict(X_val_r))})

        comparison_data.append({'Technique': tech, 'Model': 'MLP_GPU',
                                 'Accuracy': accuracy_score(y_val, run_mlp_cuda(X_tr_r, y_tr, X_val_r))})

df_final = pd.DataFrame(comparison_data)
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
sns.barplot(x='Model', y='Accuracy', hue='Technique', data=df_final,
            palette='coolwarm', ax=axes[0])
axes[0].axhline(0.90, color='gray', linestyle='--', alpha=0.5, label='90% line')
axes[0].set_title("CV Accuracy: PCA vs LDA", fontsize=13, fontweight='bold')
axes[0].set_ylim(0.5, 1.05); axes[0].legend()

sns.boxplot(x='Model', y='Accuracy', hue='Technique', data=df_final,
            palette='Set3', ax=axes[1])
axes[1].set_title("Accuracy Distribution (5 folds)", fontsize=13, fontweight='bold')
plt.suptitle("7. - Cross-Validation Results", fontsize=14, fontweight='bold')
plt.tight_layout(); plt.show()

print("\n--- CROSS-VALIDATION BENCHMARK ---")
print(df_final.groupby(['Technique', 'Model'])['Accuracy'].mean().unstack())

# --- 1. FINAL HOLDOUT EVALUATION (Keep existing calculation loop) ---
print("\n--- FINAL HOLDOUT EVALUATION ---")
final_results = []

for tech in ['PCA', 'LDA']:
    reducer       = PCA(n_components=n_components_pca) if tech == 'PCA' else LDA(n_components=1)
    X_cv_r        = reducer.fit_transform(X_cv_scaled, y_cv)
    X_holdout_r   = reducer.transform(X_holdout_scaled)

    knn = KNeighborsClassifier(n_neighbors=5, weights='distance').fit(X_cv_r, y_cv)
    final_results.append({'Technique': tech, 'Model': 'KNN',
                          'Holdout_Accuracy': accuracy_score(y_holdout, knn.predict(X_holdout_r))})

    svm = SVC(kernel='linear', C=0.5).fit(X_cv_r, y_cv)
    final_results.append({'Technique': tech, 'Model': 'SVM',
                          'Holdout_Accuracy': accuracy_score(y_holdout, svm.predict(X_holdout_r))})

    final_results.append({'Technique': tech, 'Model': 'MLP_GPU',
                          'Holdout_Accuracy': accuracy_score(y_holdout,
                                                             run_mlp_cuda(X_cv_r, y_cv, X_holdout_r))})

df_holdout = pd.DataFrame(final_results)
print(df_holdout.pivot(index='Model', columns='Technique', values='Holdout_Accuracy'))

best_row = df_holdout.loc[df_holdout['Holdout_Accuracy'].idxmax()]
print(f"\nBest: {best_row['Model']} + {best_row['Technique']} -> Holdout accuracy: {best_row['Holdout_Accuracy']:.4f}")

# --- 2. CONFUSION MATRICES FOR ALL 3 MODELS ---
# We will plot these using the best performing technique (PCA or LDA)
best_tech = best_row['Technique']
best_reducer = PCA(n_components=n_components_pca) if best_tech == 'PCA' else LDA(n_components=1)
X_cv_r_best  = best_reducer.fit_transform(X_cv_scaled, y_cv)
X_ho_r_best  = best_reducer.transform(X_holdout_scaled)

# Get predictions for all three models using the best reduction technique
knn_best = KNeighborsClassifier(n_neighbors=5, weights='distance').fit(X_cv_r_best, y_cv)
svm_best = SVC(kernel='linear', C=0.5).fit(X_cv_r_best, y_cv)

y_pred_knn = knn_best.predict(X_ho_r_best)
y_pred_svm = svm_best.predict(X_ho_r_best)
y_pred_mlp = run_mlp_cuda(X_cv_r_best, y_cv, X_ho_r_best)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
models = ['KNN', 'SVM', 'MLP']
preds = [y_pred_knn, y_pred_svm, y_pred_mlp]

for i, (m, p) in enumerate(zip(models, preds)):
    sns.heatmap(confusion_matrix(y_holdout, p), annot=True, fmt='d',
                cmap='Blues', xticklabels=le.classes_, yticklabels=le.classes_, ax=axes[i])
    axes[i].set_title(f"{m} Confusion Matrix ({best_tech})", fontweight='bold')
    axes[i].set_ylabel("True Label")
    axes[i].set_xlabel("Predicted Label")
plt.tight_layout()
plt.show()

# --- 3. 2D DECISION BOUNDARY PLOTS ---
# Note: We MUST compress the data to exactly 2 dimensions (PCA=2) to plot a 2D surface!
print("\n--- Generating 2D Decision Boundaries (PCA = 2) ---")
pca2 = PCA(n_components=2)
X_cv_2d = pca2.fit_transform(X_cv_scaled)

# Train models strictly on the 2D data
knn_2d = KNeighborsClassifier(n_neighbors=5, weights='distance').fit(X_cv_2d, y_cv)
svm_2d = SVC(kernel='linear', C=0.5).fit(X_cv_2d, y_cv)

# Create a meshgrid to map out the contour area
x_min, x_max = X_cv_2d[:, 0].min() - 1, X_cv_2d[:, 0].max() + 1
y_min, y_max = X_cv_2d[:, 1].min() - 1, X_cv_2d[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.1),
                     np.arange(y_min, y_max, 0.1))
mesh_points = np.c_[xx.ravel(), yy.ravel()]

# Predict boundaries
Z_knn = knn_2d.predict(mesh_points).reshape(xx.shape)
Z_svm = svm_2d.predict(mesh_points).reshape(xx.shape)
# run_mlp_cuda trains inside the function, we feed the mesh points as the 'test' set
Z_mlp = run_mlp_cuda(X_cv_2d, y_cv, mesh_points).reshape(xx.shape)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
Z_list = [Z_knn, Z_svm, Z_mlp]

for i, (m, Z) in enumerate(zip(models, Z_list)):
    axes[i].contourf(xx, yy, Z, alpha=0.3, cmap='coolwarm')

    # Scatter plot the real 2D training points over the boundary
    scatter = axes[i].scatter(X_cv_2d[:, 0], X_cv_2d[:, 1], c=y_cv,
                              cmap='coolwarm', edgecolors='k', s=40)
    axes[i].set_title(f"Decision Boundary: {m}", fontsize=13, fontweight='bold')
    axes[i].set_xlabel("Principal Component 1")
    axes[i].set_ylabel("Principal Component 2")

plt.suptitle("Model Decision Boundaries (Projected to 2D PCA Space)", fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

